-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgR6KWiu5Tct9oGtt1
ouPRAGow8eWmRqvugX1JaZnIxMqgCgYIKoZIzj0DAQehRANCAAS6JT/LxdGlgrT+
rF4JeUHRLyql70LaL5/cKUBEXYW3XWKaNT/bK3uHIf26rybjVLeJu6J5ro2wU7Lm
pJQrCNHK
-----END PRIVATE KEY-----
